apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-devops-project-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: retail-devops-project-deployment
  template:
    metadata:
      labels:
        app: retail-devops-project-deployment
    spec:
      containers:
        - name: retail-devops-project-deployment
          image: mkanathe/retail-devops-project:1.0.0-33
          resources:
            limits:
              memory: "250Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
