apiVersion: v1
kind: Service
metadata:
  name: retail-devops-project-service
  labels:
    app: retail-devops-project 
spec:
  selector:
    app: retail-devops-project

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
